### ISSUE TITLE
License & url

### ISSUE THREAD

**Issue by TobidieTopfpflanze** [ZeferaMC/ResourcePack#3]
FYK, the manifest metadata field also supports a license & url property:

```json
  "metadata": {
    "authors": [
      "Tobi die Topfpflanze"
    ],
    "license": "MIT",
    "url": "https://github.com/TobidieTopfpflanze"
  }
```

**Comment by ceepkev77** [comment]
Thank you!

**Comment by TobidieTopfpflanze** [comment]
You have implemented it the wrong way. You should use as URL the website for your projekt/organization. Don't just copy it the way I did it 😂
